In [1]:
import numpy as np
import pandas as pd

In [2]:
lst=['USA','Germany','Italy','Japan']
ind=['a','b','c','d']
df=pd.DataFrame(lst)
print(df)

         0
0      USA
1  Germany
2    Italy
3    Japan

In [3]:
from numpy.random import randn
np.random.seed(101)

In [4]:
df=pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())

In [5]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [6]:
df['X']

A    0.628133
B   -0.319318
C    0.740122
D   -0.758872
E    1.978757
Name: X, dtype: float64

In [7]:
df[['W','Z','X']]

          W         Z         X
A  2.706850  0.503826  0.628133
B  0.651118  0.605965 -0.319318
C -2.018168 -0.589001  0.740122
D  0.188695  0.955057 -0.758872
E  0.190794  0.683509  1.978757

In [8]:
type(df[['W','Z','X']])

pandas.DataFrame

In [9]:
df['new']=df['W']+df['Y']

In [10]:
df

          W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [12]:
df.drop('W',axis=1)

          X         Y         Z       new
A  0.628133  0.907969  0.503826  3.614819
B -0.319318 -0.848077  0.605965 -0.196959
C  0.740122  0.528813 -0.589001 -1.489355
D -0.758872 -0.933237  0.955057 -0.744542
E  1.978757  2.605967  0.683509  2.796762

In [13]:
df.drop('new',axis=1,inplace=True)

In [14]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509